'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class lab5
    Public Property id As Integer
    Public Property first_name As String
    Public Property last_name As String
    Public Property email As String
    Public Property gender As String
    Public Property ip_address As String

End Class
